import React, { useState } from "react";
import HubLayout from "@/components/hub/HubLayout";
import FAQAccordion from "@/components/hub/FAQAccordion";
import ChatBot from "@/components/hub/ChatBot";
import AEInfoCard from "@/components/hub/AEInfoCard";
import { BlurFade } from "@/components/ui/blur-fade";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useCustomer } from "@/contexts/CustomerContext";
import { mockAccountExecutive } from "@/data/mockData";
import { MessageCircle, HelpCircle } from "lucide-react";

// Enhanced FAQ data based on Lovable docs and app context
const faqItems = [
  // Getting Started
  {
    id: "gs-1",
    category: "Getting Started",
    question: "How do I get started with Lovable?",
    answer:
      "Getting started is simple: describe what you want to build in natural language, and Lovable generates production-ready code instantly. You can start from scratch or remix existing projects. No coding experience required for most use cases.",
  },
  {
    id: "gs-2",
    category: "Getting Started",
    question: "What technology stack does Lovable use?",
    answer:
      "Lovable generates applications using React 18 with TypeScript, Vite for fast builds, Tailwind CSS for styling, Shadcn/UI components, and Framer Motion for animations. This is a modern, production-ready stack used by thousands of companies.",
  },
  {
    id: "gs-3",
    category: "Getting Started",
    question: "Can non-technical team members use Lovable?",
    answer:
      "Absolutely! Lovable is designed for everyone. Product managers, designers, marketers, and business users can build and iterate without coding knowledge. Technical users can also dive into the code for advanced customizations.",
  },
  // Enterprise Features
  {
    id: "ef-1",
    category: "Enterprise Features",
    question: "What enterprise features are available?",
    answer:
      "Enterprise plans include SSO/SAML integration, role-based access control, comprehensive audit logs, custom domains, priority support, dedicated account management, and SLA guarantees. We're SOC 2 Type II certified.",
  },
  {
    id: "ef-2",
    category: "Enterprise Features",
    question: "How does Lovable work with our existing codebase?",
    answer:
      "Lovable syncs directly with your GitHub repository. You can start with existing projects or create new ones. All code is yours to own, export, and deploy anywhere. Two-way sync allows for external editing.",
  },
  {
    id: "ef-3",
    category: "Enterprise Features",
    question: "What is Lovable Cloud?",
    answer:
      "Lovable Cloud is our integrated backend service providing PostgreSQL database, authentication, file storage, edge functions, and secrets management. It enables full-stack development without external setup.",
  },
  // Pricing & Plans
  {
    id: "pp-1",
    category: "Pricing & Plans",
    question: "How does pricing work for enterprise?",
    answer:
      "Enterprise pricing is based on seats and usage. We offer custom quotes tailored to your organization's needs. Contact your Account Executive for a detailed proposal based on your specific requirements.",
  },
  {
    id: "pp-2",
    category: "Pricing & Plans",
    question: "How do credits work?",
    answer:
      "Chat mode consumes 1 credit per message. Agent mode varies based on complexity. Visual Edits are free. Credits are provided daily on all plans and monthly on paid plans. Free plan gets 5 daily credits (30/month cap).",
  },
  {
    id: "pp-3",
    category: "Pricing & Plans",
    question: "What's the typical ROI for enterprise customers?",
    answer:
      "Our enterprise customers typically see 60-80% reduction in development time and 3-5x faster time-to-market for new features. Many teams replace contractor costs entirely while shipping faster.",
  },
  // Security & Compliance
  {
    id: "sc-1",
    category: "Security & Compliance",
    question: "What security certifications does Lovable have?",
    answer:
      "Lovable is SOC 2 Type II certified with enterprise-grade security. We support SSO/SAML, role-based access control, and provide comprehensive audit logs. Data is encrypted at rest and in transit.",
  },
  {
    id: "sc-2",
    category: "Security & Compliance",
    question: "Is Lovable GDPR compliant?",
    answer:
      "Yes, Lovable is GDPR compliant. We offer data residency options for organizations with specific requirements. All user data handling follows strict privacy regulations.",
  },
  {
    id: "sc-3",
    category: "Security & Compliance",
    question: "Who owns the code generated by Lovable?",
    answer:
      "You own 100% of the code generated by Lovable. You can export it, deploy it anywhere, and use it however you like. There are no licensing restrictions on generated code.",
  },
  // Integrations
  {
    id: "in-1",
    category: "Integrations",
    question: "Can I integrate with my existing tools?",
    answer:
      "Yes! Lovable supports GitHub integration for code sync, and Lovable Cloud provides connectors for various services. Edge functions enable custom integrations with any API or service.",
  },
  {
    id: "in-2",
    category: "Integrations",
    question: "Does Lovable support AI features in my app?",
    answer:
      "Yes! Lovable AI is a gateway service providing access to Google Gemini and OpenAI models. It's pre-configured with no API key setup required. Usage-based pricing with free monthly allocation.",
  },
  // Support
  {
    id: "su-1",
    category: "Support",
    question: "What support is included with enterprise plans?",
    answer:
      "Enterprise plans include dedicated support, priority response times, custom onboarding, training sessions, and direct access to our product team. Your Account Executive is your primary point of contact.",
  },
  {
    id: "su-2",
    category: "Support",
    question: "How can I get help if I'm stuck?",
    answer:
      "You have multiple options: use this AI chatbot for instant answers, browse the FAQ, check docs.lovable.dev, join our Discord community, or reach out to your Account Executive directly.",
  },
];

const categories = [
  "all",
  "Getting Started",
  "Enterprise Features",
  "Pricing & Plans",
  "Security & Compliance",
  "Integrations",
  "Support",
];

const FAQPage: React.FC = () => {
  const { profile } = useCustomer();
  const [selectedCategory, setSelectedCategory] = useState("all");
  const [activeTab, setActiveTab] = useState<"faq" | "chat">("faq");

  return (
    <HubLayout sectionId="faq" showBackground={false}>
      <section className="pt-24 md:pt-32 pb-16 md:pb-24 bg-background rounded-3xl">
        <div className="mx-auto w-full px-4 md:px-8 lg:px-16 space-y-12">
          {/* Header */}
          <BlurFade delay={0.1}>
            <div className="max-w-2xl">
              <h1 className="text-[36px] md:text-[48px] font-semibold leading-[110%] tracking-[-0.03em] text-foreground">
                FAQ & Support
              </h1>
              <p className="text-lg text-muted-foreground mt-4">
                Get answers to common questions or chat with our AI assistant for personalized help.
                We're here to ensure {profile.companyName} has all the information needed.
              </p>
            </div>
          </BlurFade>

          {/* Mobile Tabs */}
          <BlurFade delay={0.2}>
            <div className="lg:hidden">
              <Tabs value={activeTab} onValueChange={(v) => setActiveTab(v as "faq" | "chat")}>
                <TabsList className="w-full">
                  <TabsTrigger value="faq" className="flex-1 gap-2">
                    <HelpCircle className="w-4 h-4" />
                    FAQ
                  </TabsTrigger>
                  <TabsTrigger value="chat" className="flex-1 gap-2">
                    <MessageCircle className="w-4 h-4" />
                    AI Chat
                  </TabsTrigger>
                </TabsList>
                <TabsContent value="faq" className="mt-6">
                  {/* Category Filter */}
                  <div className="flex flex-wrap gap-2 mb-6">
                    {categories.map((category) => (
                      <button
                        key={category}
                        onClick={() => setSelectedCategory(category)}
                        className={`px-3 py-1.5 text-xs rounded-full transition-all ${
                          selectedCategory === category
                            ? "bg-primary text-primary-foreground"
                            : "bg-[#F7F4ED] dark:bg-card border border-[#D8D6CF] dark:border-border text-foreground hover:bg-[#ECEAE4] dark:hover:bg-muted"
                        }`}
                      >
                        {category === "all" ? "All" : category}
                      </button>
                    ))}
                  </div>
                  <FAQAccordion items={faqItems} selectedCategory={selectedCategory} />
                </TabsContent>
                <TabsContent value="chat" className="mt-6">
                  <ChatBot />
                </TabsContent>
              </Tabs>
            </div>
          </BlurFade>

          {/* Desktop Side-by-Side */}
          <div className="hidden lg:grid lg:grid-cols-2 gap-8">
            {/* FAQ Section */}
            <BlurFade delay={0.2}>
              <div>
                <div className="flex items-center gap-2 mb-4">
                  <HelpCircle className="w-5 h-5 text-primary" />
                  <h2 className="text-xl font-medium text-foreground">
                    Common Questions
                  </h2>
                </div>
                {/* Category Filter */}
                <div className="flex flex-wrap gap-2 mb-6">
                  {categories.map((category) => (
                    <button
                      key={category}
                      onClick={() => setSelectedCategory(category)}
                      className={`px-3 py-1.5 text-xs rounded-full transition-all ${
                        selectedCategory === category
                          ? "bg-primary text-primary-foreground"
                          : "bg-[#F7F4ED] dark:bg-card border border-[#D8D6CF] dark:border-border text-foreground hover:bg-[#ECEAE4] dark:hover:bg-muted"
                      }`}
                    >
                      {category === "all" ? "All" : category}
                    </button>
                  ))}
                </div>
                <FAQAccordion items={faqItems} selectedCategory={selectedCategory} />
              </div>
            </BlurFade>

            {/* Chat Section */}
            <BlurFade delay={0.3}>
              <div>
                <div className="flex items-center gap-2 mb-4">
                  <MessageCircle className="w-5 h-5 text-primary" />
                  <h2 className="text-xl font-medium text-foreground">
                    AI Assistant
                  </h2>
                </div>
                <ChatBot />
              </div>
            </BlurFade>
          </div>

          {/* Account Executive Section */}
          <div>
            <BlurFade delay={0.4}>
              <div className="mb-6">
                <h2 className="text-2xl font-medium text-foreground">
                  Still Have Questions?
                </h2>
                <p className="text-muted-foreground mt-2">
                  Your Account Executive is ready to help with anything you need.
                </p>
              </div>
            </BlurFade>
            <BlurFade delay={0.45}>
              <AEInfoCard ae={mockAccountExecutive} />
            </BlurFade>
          </div>
        </div>
      </section>
    </HubLayout>
  );
};

export default FAQPage;
